services:
  api:
    build: .
    container_name: php-calculator-api
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - vendor:/app/vendor
    working_dir: /app

  test:
    build: .
    container_name: php-calculator-test
    command: composer test
    volumes:
      - ./:/app
      - vendor:/app/vendor
    working_dir: /app

volumes:
  vendor: